path:
  result: "results/unit2speech/twist.csv"

dataset:
  eval_dir: "data/LibriSpeech/test-clean"

speech2unit:
  model_name_or_path: "mhubert-base-25hz"
  quantizer_model_name: "kmeans"
  vocab_size: 500

asr:
  model_name_or_path: "openai/whisper-large-v3"